.TH lxqt-config "1" "2016-01-01" "LXQt 0.10.0" "LXQt System Settings"
.SH NAME
lxqt-config \- \fBLXQt\fR Settings Center for all related modules and applications
.SH SYNOPSIS
.B lxqt-config
.br
.SH DESCRIPTION
This application is a settings center of all environment related applications and
configuration software installed and registered by the \fBLXQt\fR desktop environment.
.P
.SH RELATED APPLICATIONS
.P
\fBLXQt\fR has various config applications:
.P
 * Mouse settings: (\fBlxqt-config-mouse\fR)
 * Desktop settings: (\fBlxqt-config-desktop\fR)
 * Appearance settings: (\fBlxqt-config-appearance\fR)
 * Session settings: (\fBlxqt-config-session\fR)
 * Notification settings: (\fBlxqt-config-notificationd\fR)
.P
All of this also can be find in Settings or Preferences menu, please consult the respective manpages.
.SH "REPORTING BUGS"
Report bugs to https://github.com/lxde/lxqt/issues
.SH "SEE ALSO"
.\" any module must refer to the session application, for module overview and initiation
\fBlxqt-config\fR(1)  LXQt settings Configuration Center interface
.P
\fBlxqt-config-session\fR(1)  LXQt default and autostart applications settings,
plus environment settings
.P
\fBlxqt-session\fR(1)  LXQt \fIoverview\fR and complete session environment
.P
\fBstartlxqt\fR(1)  LXQt session initialization and launch script (e.g. in \fB.xinitrc\fR)
.P
