.TH lxqt-config-appearance "1" "2016-01-01" "LXQt 0.10.0" "LXQt GUI settings"
.SH NAME
lxqt-config-appearance \- GUI appearance application of \fBLXQt\fR: The Lightweight Qt Desktop Environment
.SH SYNOPSIS
.B lxqt-config-appearance
.br
.SH DESCRIPTION
This is the central application to configure the appearance of Widgets, Icons, Themes, Fonts, and Cursors.
.SH "REPORTING BUGS"
Report bugs to: https://github.com/lxde/lxqt/issues
.SH "SEE ALSO"
.\" any module must refer to the session application, for module overview and initiation
\fBstartlxqt.1\fR  LXQt session initialization and launch script (e.g. in \fB.xinitrc\fR)
.P
\fBlxqt-session.1\fR  LXQt \fIoverview\fR and complete session environment
.P
\fBlxqt-config-session.1\fR  LXQt default and autostart applications settings,
plus environment settings
.P
\fBlxqt-config.1\fR  LXQt settings Configuration Center interface
.P
