.TH lxqt-config-appearance "1" "2016-05-01" "LXQt 0.11.0" "LXQt Appearance Settings"
.SH NAME
lxqt-config-appearance \- Appearance application of \fBLXQt\fR: The Lightweight Qt Desktop Environment
.SH SYNOPSIS
.B lxqt-config-appearance
.br
.SH DESCRIPTION
This application configures LXQt appearance settings:  Widgets, Icons, Themes, Fonts, and Cursors.
.SH "REPORTING BUGS"
Report bugs to: https://github.com/lxde/lxqt/issues
.SH "SEE ALSO"
.\" any module must refer to the session application, for module overview and initiation
\fBlxqt-config\fR(1)  LXQt settings Configuration Center interface
.P
\fBlxqt-config-session\fR(1)  LXQt default and autostart applications settings,
plus environment settings
.P
\fBlxqt-session\fR(1)  LXQt \fIoverview\fR and complete session environment
.P
\fBstartlxqt\fR(1)  LXQt session initialization and launch script (e.g. in \fB.xinitrc\fR)
.P
