.TH lxqt-config-cursor "1" "2016-01-01" "LXQt 0.10.0" "LXQt Cursor settings"
.SH NAME
lxqt-config-cursor \- Application of \fBLXQt\fR: The Lightweight Qt Desktop Environment
.SH SYNOPSIS
.B lxqt-config-cursor
.br
.SH DESCRIPTION
This is a simple GUI cursor theme configuration that also can manage theme installation
for LXQt (locally, per user only).
.SH "REPORTING BUGS"
Report bugs to https://github.com/lxde/lxqt/issues
.SH "SEE ALSO"
.\" any module must refer to the session application, for module overview and initiation
\fBlxqt-config\fR(1)  LXQt settings Configuration Center interface
.P
\fBlxqt-config-session\fR(1)  LXQt default and autostart applications settings,
plus environment settings
.P
\fBlxqt-session\fR(1)  LXQt \fIoverview\fR and complete session environment
.P
\fBstartlxqt\fR(1)  LXQt session initialization and launch script (e.g. in \fB.xinitrc\fR)
.P
